### PR TITLE
Added F7 hotkey that reloads to the home page(s)

### LINKED ISSUE #172: Hotkey reload?
We have a web app, that once the link is broken is not reloading. Restarting the kiosk app fixes it, but is there a hotkey sequence we can use to do the reload? Only way I have found to accomplish this is to F5, close it and then restart it.

### PR DESCRIPTION
**Pull request by RabsRincon**
This Pull Request closes #172 by adding a keybinding that promts a confirmation modal dialog that on "ok", reloads the kiosk to its initial page(s)

Please let me know if there is anything that should be fixed before merging, or if I screwed up somewhere.

This is compatible with my other PR, #185

### CODE REVIEW

**Comment by RabsRincon** [comment]
@mfkp can we carry the conversation of #172 here please? Thank you 😄

**Comment by mfkp** [comment]
Just commented on the issue, but also here, I wonder if the F7 key on Chromebook would interfere with changing the brightness, since that's what the key is mapped to. Or maybe F-keys don't do anything on Chromebook.

**Comment by matt-cook** [comment]
@RabsRincon ditto https://github.com/matt-cook/kiosk/pull/185#issuecomment-282771955 on this one: I'll take a look next week for the `v5.11.0` release.

**Comment by mfkp** [comment]
Hey @RabsRincon, was playing with this to fix #192. I don't really want to make a separate PR for the other hotkeys that may make merging harder, but I got it working by adding (in addition to this PR):

```js
// f3 or ctrl + r
if ((e.which == 114) || (e.which == 82 && e.ctrlKey)) {
  // just reload all the open webvivews for now
  $(window.document.body).find('webview').each(function(_, wv) {
    wv.reload();
  });
}
```

**Comment by matt-cook** [comment]
@RabsRincon just did an initial review and this looks good. I'd like to switch to the key combo @mfkp suggested though: https://github.com/matt-cook/kiosk/pull/190#issuecomment-284978128 let me know if that doesn't work for you.

**Comment by RabsRincon** [comment]
@mfkp Sorry for taking so long to answer. I can do this, yes, but I'm don't get why you reload() the webviews. Care to explain?. I can change the keybindings no problem so F7 is no more tho

**Comment by matt-cook** [comment]
I simplified this to only reset the content (versus reloading the app) and not use a dialog: https://github.com/matt-cook/kiosk/pull/208/commits/24297d43d5c798e9f7fffe7eda2411181e591dad

A reload of the entire app can still be accomplished by using CTRL+A to log in to the admin, then saving will reload the application. This is preferably since a reload of the entire app should require a password anyway.

**Pull request merged**
