### PR TITLE
Cookies/Cache etc removal on Inactivity Reset

### LINKED ISSUE #111: add option to clear cookies/data on inactivity resest
As reported in Chrome Web Store:

> I personally dont think it should maintain cookies. This does not work well with multiple users signing in at different times.

### PR DESCRIPTION
**Pull request by RabsRincon**
This PR aims to create a way of removing Cookies/Cache etc... once the Inactivity Reset is triggered, by providing a checkbox on the setup page, under Inactivity Reset option. 
It shares the code with "Clear Cache On Save".
Please let me know if there is anything that should be fixed before merging, or if I screwed up somewhere.

This PR closes #111 

It also fixed two super minor details. Those are on a different commit in case you prefer not to merge them
_main.js had a spelling mistake_
_setup.js had a variable defined twice_

### CODE REVIEW

**Comment by RamZallan** [comment]
:+1: for this! Was literally looking through the code to write a PR that solves this when I stumbled onto this one.

**Comment by mbillow** [comment]
This also resolves #142 and #175. Looking forward to this in the future!

**Comment by RabsRincon** [comment]
I think the checkbox should be moved to the Browser section of the settings page, but I'm not 100% sure. Can anyone tell me if it would be a good idea? (The clean up is made not only on inactivity reset, but on _any_ reset. Maybe also change the wording **again** to reflect it? )

**Comment by RamZallan** [comment]
@RabsRincon I think that it's in the correct section, as you placed it. That was where I would have put it, had I written the PR. I'd love to see this merged so I can use this for a project I'm working on. @matt-cook :smile:

**Comment by matt-cook** [comment]
@RabsRincon thanks for the PR! I'm traveling this week, but should able to review and hopefully merge into a `v5.11.0` release the week after.

**Comment by RamZallan** [comment]
@matt-cook hopefully this isn't too persistent, just wondering if there's an update on this being tested/merged. Thanks in advance :smile:

**Comment by matt-cook** [comment]
Not at all. Was planning on getting this in last week, so it's overdue.

**Pull request merged**
